//
// Generated By:JAX-WS RI 2.2.10 (JAXB RI IBM IBM 2.2.10-06/29/2016 1:04:38 PMforeman-)
//


package ru.neoflex.ejb.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "log", namespace = "http://ejb/neoflex/ru")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "log", namespace = "http://ejb/neoflex/ru")
public class Log {

    @XmlElement(name = "arg0", namespace = "")
    private String arg0;

    /**
     * 
     * @return
     *     returns String
     */
    public String getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(String arg0) {
        this.arg0 = arg0;
    }

}
