//
// Generated By:JAX-WS RI 2.2.10 (JAXB RI IBM IBM 2.2.10-06/29/2016 1:04:38 PMforeman-)
//


package ru.neoflex.ejb.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "logResponse", namespace = "http://ejb/neoflex/ru")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logResponse", namespace = "http://ejb/neoflex/ru")
public class LogResponse {


}
