<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="BP" targetNamespace="http://JDBCTestModule/BPArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://JDBCTestModule/BPArtifacts" xmlns:wsdl0="http://JDBCTestModule/BPInterface" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="BPInterfacePLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:BPInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="BPInterfacePLT1">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:BPInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="BPInterface.wsdl" namespace="http://JDBCTestModule/BPInterface"/>
</wsdl:definitions>