<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/input_map_req_1.map" md5sum="e0c46938e0f05dbb7cb31ceacfcc0034" version="8.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		input_map_req_1.map
*   Map declaration(s):	input_map_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FJDBCTestModule%252FBPInterface%257DcreateRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FJDBCTestModule%252FJDBCImport%257DcreateDb2adminTestRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in="wsdl.http://JDBCTestModule/BPInterface"
    xmlns:io="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/db2admintest"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in2="http://JDBCTestModule"
    xmlns:io2="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io5="http://www.w3.org/2005/08/addressing"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in3="http://JDBCTestModule/BPInterface"
    xmlns:out2="wsdl.http://JDBCTestModule/JDBCImport"
    xmlns:out3="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out4="http://com/ibm/j2ca/fault"
    xmlns:out="http://JDBCTestModule/JDBCImport"
    xmlns:DataConverter="xalan://ru.neoflex.DataConverter"
    xmlns:map="http://JDBCTestModule/xslt/input_map_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math DataConverter map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:createDb2adminTestRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:input_map_req_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:input_map_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map_req_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:createDb2adminTestRequestMsg'"/>
      </xsl:attribute>
      <out:createDb2adminTest>
        <out:createDb2adminTestInput>
          <!-- a simple mapping with no associated source:  to "id"(int) -->
          <xsl:element name="id">
            <xsl:text>1</xsl:text>
          </xsl:element>
          <!-- a simple data mapping: "in3:create/input1/name"(string) to "name"(string) -->
          <xsl:if test="in3:create/input1/name">
            <xsl:element name="name">
              <xsl:value-of select="in3:create/input1/name"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in3:create/input1/value"(string) to "value"(string) -->
          <xsl:if test="in3:create/input1/value">
            <xsl:element name="value">
              <xsl:value-of select="in3:create/input1/value"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in3:create/input1/price"(int) to "price"(decimal) -->
          <xsl:if test="in3:create/input1/price">
            <xsl:element name="price">
              <!-- variables for custom code -->
              <xsl:variable name="price" select="in3:create/input1/price"/>
              <xsl:value-of select="DataConverter:sampleTransform($price)"/>
            </xsl:element>
          </xsl:if>
        </out:createDb2adminTestInput>
      </out:createDb2adminTest>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map_req_12">
    <xsl:param name="body"/>
    <out:createDb2adminTest>
      <out:createDb2adminTestInput>
        <!-- a simple mapping with no associated source:  to "id"(int) -->
        <xsl:element name="id">
          <xsl:text>1</xsl:text>
        </xsl:element>
        <!-- a simple data mapping: "$body/in3:create/input1/name"(string) to "name"(string) -->
        <xsl:if test="$body/in3:create/input1/name">
          <xsl:element name="name">
            <xsl:value-of select="$body/in3:create/input1/name"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in3:create/input1/value"(string) to "value"(string) -->
        <xsl:if test="$body/in3:create/input1/value">
          <xsl:element name="value">
            <xsl:value-of select="$body/in3:create/input1/value"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in3:create/input1/price"(int) to "price"(decimal) -->
        <xsl:if test="$body/in3:create/input1/price">
          <xsl:element name="price">
            <!-- variables for custom code -->
            <xsl:variable name="price" select="$body/in3:create/input1/price"/>
            <xsl:value-of select="DataConverter:sampleTransform($price)"/>
          </xsl:element>
        </xsl:if>
      </out:createDb2adminTestInput>
    </out:createDb2adminTest>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
