<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/output_map_res_2.map" md5sum="d6504c4a105d107959475a24666d2a70" version="8.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		output_map_res_2.map
*   Map declaration(s):	output_map_res_2
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FJDBCTestModule%252FJDBCImport%257DretrieveDb2adminTestResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FJDBCTestModule%252FBP2Interface%257DfindResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:in5="http://com/ibm/j2ca/fault"
    xmlns:in="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/db2admintest"
    xmlns:io="http://www.w3.org/2005/08/addressing"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in2="http://JDBCTestModule/JDBCImport"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in4="http://com/ibm/j2ca/fault/afcfault"
    xmlns:in3="wsdl.http://JDBCTestModule/JDBCImport"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="wsdl.http://JDBCTestModule/BP2Interface"
    xmlns:out3="http://JDBCTestModule"
    xmlns:out="http://JDBCTestModule/BP2Interface"
    xmlns:map="http://JDBCTestModule/xslt/output_map_res_2"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:findResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:output_map_res_22">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:output_map_res_2"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_2">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:findResponseMsg'"/>
      </xsl:attribute>
      <out:findResponse>
        <!-- a simple data mapping: "in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/id"(int) to "output1"(string) -->
        <xsl:element name="output1">
          <xsl:value-of select="concat(in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/id, ' ', in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/name, ' ', in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/value, ' ', in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/price, ' ')"/>
        </xsl:element>
      </out:findResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_22">
    <xsl:param name="body"/>
    <out:findResponse>
      <!-- a simple data mapping: "$body/in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/id"(int) to "output1"(string) -->
      <xsl:element name="output1">
        <xsl:value-of select="concat($body/in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/id, ' ', $body/in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/name, ' ', $body/in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/value, ' ', $body/in2:retrieveDb2adminTestResponse/in2:retrieveDb2adminTestOutput/price, ' ')"/>
      </xsl:element>
    </out:findResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
