<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/output_map_res_1.map" md5sum="ce51f3db57aa60cd860579817cc28b3c" version="8.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM Graphical Data Mapping Editor.
*   Version 8.0.5.0
*
*   Mapping file:		output_map_res_1.map
*   Map declaration(s):	output_map_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FJDBCTestModule%252FJDBCImport%257DcreateDb2adminTestResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FJDBCTestModule%252FBPInterface%257DcreateResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:str="http://exslt.org/strings"
    xmlns:exsl="http://exslt.org/common"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:in="http://JDBCTestModule/JDBCImport"
    xmlns:io="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/db2admintest"
    xmlns:in2="wsdl.http://JDBCTestModule/JDBCImport"
    xmlns:io3="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.w3.org/2005/08/addressing"
    xmlns:in4="http://com/ibm/j2ca/fault"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in3="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out2="http://JDBCTestModule"
    xmlns:out3="http://JDBCTestModule/BPInterface"
    xmlns:out="wsdl.http://JDBCTestModule/BPInterface"
    xmlns:map="http://JDBCTestModule/xslt/output_map_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="date str exsl set math map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out:createResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:output_map_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:output_map_res_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:createResponseMsg'"/>
      </xsl:attribute>
      <out3:createResponse>
        <!-- a structural mapping: "in:createDb2adminTestResponse/in:createDb2adminTestOutput"(Db2adminTest) to "output1"(Db2adminTest) -->
        <xsl:element name="output1">
          <xsl:call-template name="copyNamespaceDeclarations">
            <xsl:with-param name="root" select="in:createDb2adminTestResponse/in:createDb2adminTestOutput"/>
          </xsl:call-template>
          <xsl:copy-of select="in:createDb2adminTestResponse/in:createDb2adminTestOutput/@*|in:createDb2adminTestResponse/in:createDb2adminTestOutput/node()"/>
        </xsl:element>
      </out3:createResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_12">
    <xsl:param name="body"/>
    <out3:createResponse>
      <!-- a structural mapping: "$body/in:createDb2adminTestResponse/in:createDb2adminTestOutput"(Db2adminTest) to "output1"(Db2adminTest) -->
      <xsl:element name="output1">
        <xsl:call-template name="copyNamespaceDeclarations">
          <xsl:with-param name="root" select="$body/in:createDb2adminTestResponse/in:createDb2adminTestOutput"/>
        </xsl:call-template>
        <xsl:copy-of select="$body/in:createDb2adminTestResponse/in:createDb2adminTestOutput/@*|$body/in:createDb2adminTestResponse/in:createDb2adminTestOutput/node()"/>
      </xsl:element>
    </out3:createResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
