<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="BP2Division" targetNamespace="http://SecondModule/BP2DivisionArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://SecondModule/BP2DivisionArtifacts" xmlns:wsdl0="http://SecondModule/BP2InterfaceDiv" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="BP2InterfaceDivPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:BP2InterfaceDiv"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="BP2InterfaceDivPLT1">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:BP2InterfaceDiv"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="BP2InterfaceDiv.wsdl" namespace="http://SecondModule/BP2InterfaceDiv"/>
</wsdl:definitions>